name = "boar-park-db-bkp-worker"
main = "src/index.js"
compatibility_date = "2025-04-07"

[observability]
enabled = true

[triggers]
crons = ["0 0 * * *"]

[[r2_buckets]]
binding = "BoarParkDBBkp"
bucket_name = "boar-park-db-backup"

[[workflows]]
name = "boardb-backup-workflow"
binding = "BACKUP_WORKFLOW"
class_name = "backupWorkflow"
